obj-$(CONFIG_MSM_VIDC_V4L2) += vidc/
obj-$(CONFIG_MSM_WFD) += wfd/
obj-$(CONFIG_DVB_MPQ) += dvb/

ifeq ($(CONFIG_SEC_H_PROJECT),y)
obj-$(CONFIG_MSMB_CAMERA) += camera_h/
else
obj-$(CONFIG_MSMB_CAMERA) += camera_v2/
endif
obj-y += vcap/
