#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_SENSORS_SSP_ATMEL)	+= atmel/
obj-$(CONFIG_SENSORS_SSP_STM)	+= stm/
obj-$(CONFIG_SENSORS_SSP_STM_MONTBLANC)	+= stm_montblanc/
