ccflags-y += -Idrivers/media/platform/msm/camera_h
ccflags-y += -Idrivers/media/platform/msm/camera_h/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_h/sensor/cci
obj-$(CONFIG_MSM_EEPROM) += msm_eeprom.o
