ccflags-y += -Idrivers/media/platform/msm/camera_h
ccflags-y += -Idrivers/media/platform/msm/camera_h/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_h/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
