ccflags-y += -Idrivers/media/platform/msm/camera_h
ccflags-y += -Idrivers/media/platform/msm/camera_h/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_h/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
